---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: build-template
  system: dino-dush
  app: user-management
  kind: quarkus
metadata:
  name: build-template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: '${APP_NAME}'
      system: dino-dush
      kind: quarkus
    name: '${APP_NAME}'
  spec: {}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: 'ubi-quarkus-native-s2i'
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: 'quay.io/quarkus/ubi-quarkus-native-s2i:19.0.2'
      generation: 2
      importPolicy: {}
      name: 19.0.2
      referencePolicy:
        type: Source
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${APP_NAME}
      system: dino-dush
      kind: quarkus
    name: ${APP_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    postCommit: {}
    output:
      to:
        kind: ImageStreamTag
        name: '${APP_NAME}:${BUILD_TAG}'
    resources:
      limits:
        cpu: '${CPU_LIMIT}'
        memory: '${MEMORY_LIMIT}'
      requests:
        cpu: '${CPU_REQUEST}'
        memory: '${MEMORY_REQUEST}'
    runPolicy: Serial
    source:
      contextDir: ${GIT_CONTEXT_DIR}
      git:
        ref: ${GIT_BRANCH}
        uri: '${GIT_URL}'
      type: Git
      sourceSecret:
        name: "${SOURCE_SECRET}"
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'ubi-quarkus-native-s2i:19.0.2'
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers: []
  status: {}
parameters:
- name: CPU_REQUEST
  required: true
  value: 100m
- name: CPU_LIMIT
  required: true
  value: 200m
- name: MEMORY_REQUEST
  required: true
  value: 100Mi
- name: MEMORY_LIMIT
  required: true
  value: 200Mi
- name: APP_NAME
  required: true
  value: user-management
- name: BUILD_TAG
  required: true
  value: latest
- name: GIT_URL
  required: true
  value: https://github.com/cnad-io/wsao-1-back.git
- name: GIT_BRANCH
  required: true
  value: master
- name: GIT_CONTEXT_DIR
- name: SOURCE_SECRET
  value: git-auth
