apiVersion: "v1"
kind: "BuildConfig"
metadata:
  name: "pipeline-wsao-game-room"
spec:
  source:
    git:
      ref: develop
      uri: 'https://github.com/cnad-io/wsao-1-back.git'
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipelines/jenkinsfile
      env:
        - name: namespace
          value: wsao
        - name: buildconfig
          value: game-room
        - name: deploymentconfig
          value: game-room
        - name: openshiftobjectsfolder
          value: game-room/ocp_resources
    type: JenkinsPipeline
