apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: game-room
  name: game-room
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: game-room:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /game-room
    git:
      ref: develop
      uri: https://github.com/cnad-io/wsao-1-back.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - generic:
      secret: 74dd467176784226
    type: Generic
  - github:
      secret: c59f5e1156f83419
    type: GitHub
  - imageChange:
      lastTriggeredImageID: docker-registry.default.svc:5000/openshift/nodejs@sha256:bce9d648821108fb7046b33b6f3f1b49607fd44a242de2a6a0a538f56e353153
    type: ImageChange
  - type: ConfigChange
